name: CI - FastAPI Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t fastapi-app:ci .

    - name: Run and test container
      run: |
        docker run -d -p 8000:8000 --name test-api fastapi-app:ci
        sleep 5
        curl --fail http://localhost:8000/docs || exit 1
